### ISSUE TITLE
Creating tenant in tests

### ISSUE THREAD

**Issue by 0urobor0s** [ateliware/triplex#67]
Saw #61 but I still get an error 
`{:error, "connection not available and request was dropped from queue after XXms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information"}`
For context I'm calling `Triplex.create` inside the test.

**Comment by churcho** [comment]
Try the option described [here](https://github.com/ateliware/triplex/issues/47#issuecomment-344141992rl)

That worked for me.

I decided to ignore tests to check if Triplex.create works because that's essentially testing the module again.

**Comment by 0urobor0s** [comment]
Yes, for the first tenant creation that works, the problem is that the application needs to create a tenant on demand from a request. That's what I'm testing.

**Comment by churcho** [comment]
Same issue I had. 

I just resolved that "If it can make one, it can make another if I pass the right params" so instead of testing Tenant.create, I test my logic that handles that request.

It's sort of like testing GenServer calls and not the entire GenServer process. I know it's limiting but it works.

**Comment by 0urobor0s** [comment]
After seeing how `Ecto.Adapters.SQL.Sandbox` works I figured how to run the tests I wanted.
The solution was to tag the test as `async: false` and in the setup of said test using `:ok = Ecto.Adapters.SQL.Sandbox.mode(MyApp.Repo, :auto)`
