### ISSUE TITLE
`mix triplex.migrate` didn't migrate public

### ISSUE THREAD

**Issue by yz-ark7** [ateliware/triplex#72]
After move priv/repo/migration to priv/repo/tenant_migrations, `mix ecto.migrate` is not working anymore. Should `mix triplex.migrate` also migrate the public prefix?

**Comment by mgiacomini** [comment]
Have you removed the *priv/repo/migrations* directory?

If you want to use the same migrations for the public and for the tenants you can configure Ecto migrations path to use the same. If not, just use the default path for the public (priv/repo/migrations).

**Comment by kelvinst** [comment]
That is actually the expected behaviour, `mix triplex.*` operate only on the tenant schemas, and as @mgiacomini pointed, will run the migrations on `priv/repo/tenant_migrations`... If you want `public` and tenant schemas to be the same, point triplex migration dir to `priv/repo/migrations`, but still you will need to run `mix do triple.migrate, ecto.migrate`, as the triplex tasks will still only run for the tenant schemas, there is already `ecto.migrate` for the `public` one.
